baseURL = 'https://muskrattrap.jjgroenendijk.nl/'
languageCode = 'en-us'
title = 'Muskrat Trap'
theme = "hugo-book"
enableGitInfo = true

[params]
    BookRepo = 'https://github.com/jjgroenendijk/muskrattrap'
    BookCommitPath = 'commit'
    BookEditPath = 'edit/main/website'
    BookSection = '*'

[menu]
# [[menu.before]]

[[menu.after]]
  name = "Github"
  url = "https://github.com/jjgroenendijk/muskrattrap"
  weight = 10

[[menu.after]]
  name = "Node-RED"
  url = "https://iot.jjgroenendijk.nl/"
  weight = 20

[[menu.after]]
  name = "Muskusrat recept"
  url = "https://oogstenzonderzaaien.nl/2012/01/recept-muskusrat/"
  weight = 30
  